#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Oct 11, 2020 10:40:31 PM WAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unicode_viewer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    unicode_viewer_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    unicode_viewer_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font13 = "-family {Times New Roman} -size 48 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("336x430")
        top.title("Unicode Viewer")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.06, rely=0.07, height=163, width=303)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font13)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(relief="raised")
        self.Label1.configure(text='''Label''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.238, rely=0.907, height=28, width=72)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Previous''')

        self.Button1_1 = tk.Button(top)
        self.Button1_1.place(relx=0.536, rely=0.907, height=28, width=59)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Next''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.387, rely=0.814,height=20, relwidth=0.31)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Courier New} -size 10")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.06, rely=0.535, height=23, width=109)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Max = 1114112''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.089, rely=0.605, height=23, width=58)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Min = 0''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.595, rely=0.558, height=23, width=58)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Current''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.774, rely=0.558, height=23, width=22)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''34''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.238, rely=0.814, height=23, width=42)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(relief="groove")
        self.Label6.configure(text='''Surf''')

if __name__ == '__main__':
    vp_start_gui()





