#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 17, 2020 06:22:37 PM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #004000
set vTcl(actual_gui_menu_fg) #ffff00
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #203f00
set vTcl(active_menu_fg) #111111
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m61" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 912x340
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "DC Account"
    vTcl:DefineAlias "$top" "DCAccount" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m61
    menu $site_3_0 \
        -activebackground #203f00 -activeforeground #111111 \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab71 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Object Details} -background $vTcl(actual_gui_bg) -height 328 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 260 
    vTcl:DefineAlias "$top.lab71" "Labelframe1" vTcl:WidgetProc "DCAccount" 1
    set site_3_0 $top.lab71
    label $site_3_0.lab72 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -relief groove -text Region 
    vTcl:DefineAlias "$site_3_0.lab72" "Label2" vTcl:WidgetProc "DCAccount" 1
    button $site_3_0.but73 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief sunken -text {Apata Miracle Peter} 
    vTcl:DefineAlias "$site_3_0.but73" "Button2" vTcl:WidgetProc "DCAccount" 1
    labelframe $site_3_0.lab74 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Subs \
        -background $vTcl(actual_gui_bg) -height 148 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 214 
    vTcl:DefineAlias "$site_3_0.lab74" "Labelframe1" vTcl:WidgetProc "DCAccount" 1
    set site_4_0 $site_3_0.lab74
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr75 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr75" "Scrolledlistbox1" vTcl:WidgetProc "DCAccount" 1

    $site_4_0.scr75.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font11 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_4_0.scr75 \
        -in $site_4_0 -x 7 -y 20 -width 218 -height 150 -anchor nw \
        -bordermode ignore 
    checkbutton $site_3_0.che76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Dialog? -variable che76 
    vTcl:DefineAlias "$site_3_0.che76" "Checkbutton1" vTcl:WidgetProc "DCAccount" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text {Total Subs} 
    vTcl:DefineAlias "$site_3_0.lab78" "Label1_3" vTcl:WidgetProc "DCAccount" 1
    label $site_3_0.lab79 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 6 
    vTcl:DefineAlias "$site_3_0.lab79" "Label1_1" vTcl:WidgetProc "DCAccount" 1
    ttk::combobox $site_3_0.tCo81 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo81" "TCombobox1" vTcl:WidgetProc "DCAccount" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 10 -y 30 -width 73 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but73 \
        -in $site_3_0 -x 90 -y 30 -width 156 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 10 -y 124 -width 237 -relwidth 0 -height 179 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che76 \
        -in $site_3_0 -x 150 -y 60 -width 95 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 10 -y 100 -width 123 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 140 -y 100 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo81 \
        -in $site_3_0 -x 10 -y 60 -width 83 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr77 \
        -background $vTcl(actual_gui_bg) -height 307 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 620 
    vTcl:DefineAlias "$top.scr77" "Scrolledtreeview2" vTcl:WidgetProc "DCAccount" 1
        .top42.scr77.01 configure -columns {Col1}
        .top42.scr77.01 heading #0 -text {Tree}
        .top42.scr77.01 heading #0 -anchor center
        .top42.scr77.01 column #0 -width 300
        .top42.scr77.01 column #0 -minwidth 20
        .top42.scr77.01 column #0 -stretch 1
        .top42.scr77.01 column #0 -anchor w
        .top42.scr77.01 heading Col1 -text {Col1}
        .top42.scr77.01 heading Col1 -anchor center
        .top42.scr77.01 column Col1 -width 301
        .top42.scr77.01 column Col1 -minwidth 20
        .top42.scr77.01 column Col1 -stretch 1
        .top42.scr77.01 column Col1 -anchor w
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab71 \
        -in $top -x 10 -y 10 -width 260 -relwidth 0 -height 328 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr77 \
        -in $top -x 280 -y 20 -width 620 -relwidth 0 -height 311 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

