#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 01, 2020 03:08:47 AM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #800080
set vTcl(actual_gui_fg) #ffffff
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #004000
set vTcl(actual_gui_menu_fg) #ffff00
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #203f00
set vTcl(active_menu_fg) #111111
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 836x646
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 605 -width 685 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    frame $site_3_0.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 295 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 425 
    vTcl:DefineAlias "$site_3_0.fra45" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra45
    canvas $site_4_0.can87 \
        -background #ffff00 -borderwidth 2 -closeenough 1.0 -height 293 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief groove -selectbackground #c4c4c4 \
        -selectforeground black -width 423 
    vTcl:DefineAlias "$site_4_0.can87" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.can87
    place $site_4_0.can87 \
        -in $site_4_0 -x 5 -y 5 -width 415 -relwidth 0 -height 285 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 295 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 425 
    vTcl:DefineAlias "$site_3_0.fra46" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra46
    canvas $site_4_0.can87 \
        -background #ffff00 -borderwidth 2 -closeenough 1.0 -height 293 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief groove -selectbackground #c4c4c4 \
        -selectforeground black -width 423 
    vTcl:DefineAlias "$site_4_0.can87" "Canvas1_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.can87
    place $site_4_0.can87 \
        -in $site_4_0 -x 5 -y 5 -width 415 -relwidth 0 -height 285 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab47 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Incomes \
        -background $vTcl(actual_gui_bg) -height 123 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 243 
    vTcl:DefineAlias "$site_3_0.lab47" "Labelframe1_7" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab47
    label $site_4_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 50,000} 
    vTcl:DefineAlias "$site_4_0.lab59" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Savings 
    vTcl:DefineAlias "$site_4_0.lab68" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 3,000,000} 
    vTcl:DefineAlias "$site_4_0.lab71" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Transfers 
    vTcl:DefineAlias "$site_4_0.lab72" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_4_0.lab73" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab59 \
        -in $site_4_0 -x 140 -y 60 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab68 \
        -in $site_4_0 -x 10 -y 60 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab71 \
        -in $site_4_0 -x 10 -y 20 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab72 \
        -in $site_4_0 -x 10 -y 90 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab73 \
        -in $site_4_0 -x 140 -y 90 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab48 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Debits \
        -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 240 
    vTcl:DefineAlias "$site_3_0.lab48" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab48
    label $site_4_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Withdrawals 
    vTcl:DefineAlias "$site_4_0.lab58" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 50,000} 
    vTcl:DefineAlias "$site_4_0.lab59" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Paidouts 
    vTcl:DefineAlias "$site_4_0.lab60" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 80,000} 
    vTcl:DefineAlias "$site_4_0.lab62" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab58 \
        -in $site_4_0 -x 10 -y 70 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 140 -y 70 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab60 \
        -in $site_4_0 -x 10 -y 100 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 140 -y 100 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 10 -y 20 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab49 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text Upfronts -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 240 
    vTcl:DefineAlias "$site_3_0.lab49" "Labelframe1_6" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab49
    label $site_4_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Repaid 
    vTcl:DefineAlias "$site_4_0.lab58" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 850,000} 
    vTcl:DefineAlias "$site_4_0.lab59" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Overdue 
    vTcl:DefineAlias "$site_4_0.lab60" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 130,000} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 980,000} 
    vTcl:DefineAlias "$site_4_0.lab62" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab58 \
        -in $site_4_0 -x 10 -y 70 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 140 -y 70 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab60 \
        -in $site_4_0 -x 10 -y 100 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 140 -y 100 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 10 -y 20 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab50 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text Balances -background $vTcl(actual_gui_bg) -height 165 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 240 
    vTcl:DefineAlias "$site_3_0.lab50" "Labelframe1_8" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab50
    label $site_4_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 50,000} 
    vTcl:DefineAlias "$site_4_0.lab59" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 1,080,000} 
    vTcl:DefineAlias "$site_4_0.lab62" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text B-T-Os 
    vTcl:DefineAlias "$site_4_0.lab81" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Deficits 
    vTcl:DefineAlias "$site_4_0.lab82" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Excesses 
    vTcl:DefineAlias "$site_4_0.lab83" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab84 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_4_0.lab84" "Label2_9" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab59 \
        -in $site_4_0 -x 140 -y 70 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 140 -y 100 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 10 -y 20 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab81 \
        -in $site_4_0 -x 10 -y 70 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab82 \
        -in $site_4_0 -x 10 -y 100 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab83 \
        -in $site_4_0 -x 10 -y 130 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab84 \
        -in $site_4_0 -x 140 -y 130 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra45 \
        -in $site_3_0 -x 260 -y 2 -width 425 -height 295 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra46 \
        -in $site_3_0 -x 260 -y 308 -width 425 -height 295 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 2 -y 2 -width 243 -height 123 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 2 -y 140 -width 240 -height 135 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 2 -y 290 -width 240 -height 135 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 2 -y 438 -width 240 -height 165 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 150 -y 30 -width 685 -relwidth 0 -height 605 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

