#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 03, 2020 06:23:32 AM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1047x646
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Areas 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text 006 
    vTcl:DefineAlias "$top.lab44" "Label2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra52 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 605 -highlightbackground #ff8040 -highlightcolor black \
        -width 685 
    vTcl:DefineAlias "$top.fra52" "Frame1_11" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra52
    frame $site_3_0.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 295 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 425 
    vTcl:DefineAlias "$site_3_0.fra45" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra45
    canvas $site_4_0.can87 \
        -background #ffff00 -borderwidth 2 -closeenough 1.0 -height 293 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief groove -selectbackground #c4c4c4 \
        -selectforeground black -width 423 
    vTcl:DefineAlias "$site_4_0.can87" "Canvas1_12" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.can87
    place $site_4_0.can87 \
        -in $site_4_0 -x 5 -y 5 -width 415 -relwidth 0 -height 285 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 295 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 425 
    vTcl:DefineAlias "$site_3_0.fra46" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra46
    canvas $site_4_0.can87 \
        -background #ffff00 -borderwidth 2 -closeenough 1.0 -height 293 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief groove -selectbackground #c4c4c4 \
        -selectforeground black -width 423 
    vTcl:DefineAlias "$site_4_0.can87" "Canvas1_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.can87
    place $site_4_0.can87 \
        -in $site_4_0 -x 5 -y 5 -width 415 -relwidth 0 -height 285 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra43 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 585 -width 235 
    vTcl:DefineAlias "$site_3_0.fra43" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra43
    labelframe $site_4_0.lab44 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Incomes \
        -background $vTcl(actual_gui_bg) -height 143 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 243 
    vTcl:DefineAlias "$site_4_0.lab44" "Labelframe1_7" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab44
    label $site_5_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 50,000} 
    vTcl:DefineAlias "$site_5_0.lab59" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Savings 
    vTcl:DefineAlias "$site_5_0.lab68" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 3,000,000} 
    vTcl:DefineAlias "$site_5_0.lab71" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Transfers 
    vTcl:DefineAlias "$site_5_0.lab72" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_5_0.lab73" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Commissions 
    vTcl:DefineAlias "$site_5_0.lab43" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_5_0.lab44" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab59 \
        -in $site_5_0 -x 140 -y 60 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab68 \
        -in $site_5_0 -x 10 -y 61 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab71 \
        -in $site_5_0 -x 10 -y 21 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab72 \
        -in $site_5_0 -x 10 -y 90 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab73 \
        -in $site_5_0 -x 140 -y 89 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab43 \
        -in $site_5_0 -x 10 -y 118 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab44 \
        -in $site_5_0 -x 140 -y 118 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_4_0.lab44
    labelframe $site_4_0.lab45 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Debits \
        -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 240 
    vTcl:DefineAlias "$site_4_0.lab45" "Labelframe1_6" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab45
    label $site_5_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Withdrawals 
    vTcl:DefineAlias "$site_5_0.lab58" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 50,000} 
    vTcl:DefineAlias "$site_5_0.lab59" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Paidouts 
    vTcl:DefineAlias "$site_5_0.lab60" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_5_0.lab61" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 80,000} 
    vTcl:DefineAlias "$site_5_0.lab62" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab58 \
        -in $site_5_0 -x 10 -y 61 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab59 \
        -in $site_5_0 -x 140 -y 62 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab60 \
        -in $site_5_0 -x 10 -y 91 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab61 \
        -in $site_5_0 -x 140 -y 91 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab62 \
        -in $site_5_0 -x 10 -y 21 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_4_0.lab45
    labelframe $site_4_0.lab46 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text Upfronts -background $vTcl(actual_gui_bg) -height 135 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 240 
    vTcl:DefineAlias "$site_4_0.lab46" "Labelframe1_4" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab46
    label $site_5_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Repaid 
    vTcl:DefineAlias "$site_5_0.lab58" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 850,000} 
    vTcl:DefineAlias "$site_5_0.lab59" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Overdue 
    vTcl:DefineAlias "$site_5_0.lab60" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 130,000} 
    vTcl:DefineAlias "$site_5_0.lab61" "Label2_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 980,000} 
    vTcl:DefineAlias "$site_5_0.lab62" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab58 \
        -in $site_5_0 -x 10 -y 59 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab59 \
        -in $site_5_0 -x 140 -y 58 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab60 \
        -in $site_5_0 -x 10 -y 88 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab61 \
        -in $site_5_0 -x 140 -y 87 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab62 \
        -in $site_5_0 -x 10 -y 20 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_4_0.lab46
    labelframe $site_4_0.lab47 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text Balances -background $vTcl(actual_gui_bg) -height 185 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 240 
    vTcl:DefineAlias "$site_4_0.lab47" "Labelframe1_8" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab47
    label $site_5_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 500,000} 
    vTcl:DefineAlias "$site_5_0.lab59" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_5_0.lab61" "Label2_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 1,080,000} 
    vTcl:DefineAlias "$site_5_0.lab62" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text B-T-Os 
    vTcl:DefineAlias "$site_5_0.lab81" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Deficits 
    vTcl:DefineAlias "$site_5_0.lab82" "Label1_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Excesses 
    vTcl:DefineAlias "$site_5_0.lab83" "Label1_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab84 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_5_0.lab84" "Label2_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Brought-Fs 
    vTcl:DefineAlias "$site_5_0.lab45" "Label1_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text {₦ 30,000} 
    vTcl:DefineAlias "$site_5_0.lab46" "Label2_11" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab59 \
        -in $site_5_0 -x 140 -y 60 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab61 \
        -in $site_5_0 -x 140 -y 90 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab62 \
        -in $site_5_0 -x 10 -y 20 -width 223 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab81 \
        -in $site_5_0 -x 10 -y 90 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab82 \
        -in $site_5_0 -x 10 -y 120 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab83 \
        -in $site_5_0 -x 10 -y 150 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab84 \
        -in $site_5_0 -x 140 -y 120 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab45 \
        -in $site_5_0 -x 10 -y 60 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab46 \
        -in $site_5_0 -x 140 -y 150 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_4_0.lab47
    place $site_4_0.lab44 \
        -in $site_4_0 -x 5 -y 5 -width 243 -height 149 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 5 -y 156 -width 243 -height 123 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 5 -y 285 -width 243 -height 119 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 5 -y 407 -width 243 -height 183 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra45 \
        -in $site_3_0 -x 260 -y 2 -width 425 -height 295 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra46 \
        -in $site_3_0 -x 260 -y 308 -width 425 -height 295 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra43 \
        -in $site_3_0 -x 2 -y 2 -width 253 -relwidth 0 -height 601 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra56 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 555 -highlightbackground #ff8040 -highlightcolor black \
        -width 345 
    vTcl:DefineAlias "$top.fra56" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra56
    labelframe $site_3_0.lab57 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Month \
        -background $vTcl(actual_gui_bg) -height 165 \
        -highlightbackground #ff8040 -highlightcolor black -width 330 
    vTcl:DefineAlias "$site_3_0.lab57" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab57
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 17 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text December 
    vTcl:DefineAlias "$site_4_0.lab61" "Label1_14" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Times New Roman} -size 17 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text 2020 
    vTcl:DefineAlias "$site_4_0.lab62" "Label1_15" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text Clients 
    vTcl:DefineAlias "$site_4_0.lab63" "Label1_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -anchor ne \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief sunken -text 340 
    vTcl:DefineAlias "$site_4_0.lab64" "Label2_9" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Prev 
    vTcl:DefineAlias "$site_4_0.but65" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Current 
    vTcl:DefineAlias "$site_4_0.but68" "Button1_9" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Next 
    vTcl:DefineAlias "$site_4_0.but69" "Button1_10" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab61 \
        -in $site_4_0 -x 20 -y 20 -width 183 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 220 -y 20 -width 93 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab63 \
        -in $site_4_0 -x 20 -y 70 -width 113 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab64 \
        -in $site_4_0 -x 160 -y 70 -width 93 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but65 \
        -in $site_4_0 -x 20 -y 130 -anchor nw -bordermode ignore 
    place $site_4_0.but68 \
        -in $site_4_0 -x 130 -y 130 -width 65 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but69 \
        -in $site_4_0 -x 260 -y 130 -width 45 -height 28 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab60 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Sort and Search} -background $vTcl(actual_gui_bg) -height 265 \
        -highlightbackground #ff8040 -highlightcolor black -width 330 
    vTcl:DefineAlias "$site_3_0.lab60" "Labelframe1_13" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_3_0.lab70 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Date and Time} -background $vTcl(actual_gui_bg) -height 85 \
        -highlightbackground #ff8040 -highlightcolor black -width 330 
    vTcl:DefineAlias "$site_3_0.lab70" "Labelframe1_9" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab70
    label $site_4_0.lab71 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief ridge -text {03 : 23 AM} 
    vTcl:DefineAlias "$site_4_0.lab71" "Label3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.lab71
    label $site_4_0.lab72 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief ridge -text {Tuesday 1, December 2020} 
    vTcl:DefineAlias "$site_4_0.lab72" "Label3_11" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.lab72
    place $site_4_0.lab71 \
        -in $site_4_0 -x 10 -y 22 -width 103 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab72 \
        -in $site_4_0 -x 130 -y 22 -width 193 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 10 -y 80 -width 330 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 10 -y 280 -width 330 -relwidth 0 -height 265 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 10 -y 10 -width 330 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 40 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 150 -y 40 -width 103 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra52 \
        -in $top -x 360 -y 40 -width 685 -height 605 -anchor nw \
        -bordermode ignore 
    place $top.fra56 \
        -in $top -x 10 -y 90 -width 345 -relwidth 0 -height 555 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

