#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 01, 2020 03:08:04 AM WAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import dc_dashboard_details_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    dc_dashboard_details_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    dc_dashboard_details_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#800080'  # Closest X11 color: 'magenta4'
        _fgcolor = '#ffffff'  # X11 color: 'white'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("836x646")
        top.title("New Toplevel")
        top.configure(background="#800080")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.179, rely=0.046, relheight=0.937
                , relwidth=0.819)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#800080")

        self.Frame1_1 = tk.Frame(self.Frame1)
        self.Frame1_1.place(relx=0.38, rely=0.0, relheight=0.488, relwidth=0.62)
        self.Frame1_1.configure(relief='groove')
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief="groove")
        self.Frame1_1.configure(background="#800080")
        self.Frame1_1.configure(highlightbackground="#800080")
        self.Frame1_1.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(self.Frame1_1)
        self.Canvas1.place(relx=0.012, rely=0.017, relheight=0.966
                , relwidth=0.976)
        self.Canvas1.configure(background="#ffff00")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#800080")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="groove")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.Frame1_2 = tk.Frame(self.Frame1)
        self.Frame1_2.place(relx=0.38, rely=0.504, relheight=0.488
                , relwidth=0.62)
        self.Frame1_2.configure(relief='groove')
        self.Frame1_2.configure(borderwidth="2")
        self.Frame1_2.configure(relief="groove")
        self.Frame1_2.configure(background="#800080")
        self.Frame1_2.configure(highlightbackground="#800080")
        self.Frame1_2.configure(highlightcolor="black")

        self.Canvas1_3 = tk.Canvas(self.Frame1_2)
        self.Canvas1_3.place(relx=0.012, rely=0.017, relheight=0.966
                , relwidth=0.976)
        self.Canvas1_3.configure(background="#ffff00")
        self.Canvas1_3.configure(borderwidth="2")
        self.Canvas1_3.configure(highlightbackground="#800080")
        self.Canvas1_3.configure(highlightcolor="black")
        self.Canvas1_3.configure(insertbackground="black")
        self.Canvas1_3.configure(relief="groove")
        self.Canvas1_3.configure(selectbackground="#c4c4c4")
        self.Canvas1_3.configure(selectforeground="black")

        self.Labelframe1_7 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_7.place(relx=0.0, rely=0.0, relheight=0.203
                , relwidth=0.355)
        self.Labelframe1_7.configure(relief='groove')
        self.Labelframe1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_7.configure(foreground="black")
        self.Labelframe1_7.configure(text='''Incomes''')
        self.Labelframe1_7.configure(background="#800080")
        self.Labelframe1_7.configure(highlightbackground="#800080")
        self.Labelframe1_7.configure(highlightcolor="black")

        self.Label2_7 = tk.Label(self.Labelframe1_7)
        self.Label2_7.place(relx=0.576, rely=0.488, height=23, width=93
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(anchor='ne')
        self.Label2_7.configure(background="#800080")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_7.configure(foreground="#ffffff")
        self.Label2_7.configure(highlightbackground="#800080")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''₦ 50,000''')

        self.Label1_6 = tk.Label(self.Labelframe1_7)
        self.Label1_6.place(relx=0.041, rely=0.488, height=23, width=113
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#800080")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_6.configure(foreground="#ffffff")
        self.Label1_6.configure(highlightbackground="#800080")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(relief="groove")
        self.Label1_6.configure(text='''Savings''')

        self.Label2_4 = tk.Label(self.Labelframe1_7)
        self.Label2_4.place(relx=0.041, rely=0.163, height=33, width=223
                , bordermode='ignore')
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(background="#800080")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_4.configure(foreground="#ffffff")
        self.Label2_4.configure(highlightbackground="#800080")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(justify='left')
        self.Label2_4.configure(relief="sunken")
        self.Label2_4.configure(text='''₦ 3,000,000''')

        self.Label1_5 = tk.Label(self.Labelframe1_7)
        self.Label1_5.place(relx=0.041, rely=0.732, height=23, width=113
                , bordermode='ignore')
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#800080")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_5.configure(foreground="#ffffff")
        self.Label1_5.configure(highlightbackground="#800080")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(relief="groove")
        self.Label1_5.configure(text='''Transfers''')

        self.Label2_6 = tk.Label(self.Labelframe1_7)
        self.Label2_6.place(relx=0.576, rely=0.732, height=23, width=93
                , bordermode='ignore')
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(anchor='ne')
        self.Label2_6.configure(background="#800080")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_6.configure(foreground="#ffffff")
        self.Label2_6.configure(highlightbackground="#800080")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(justify='left')
        self.Label2_6.configure(relief="sunken")
        self.Label2_6.configure(text='''₦ 30,000''')

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.0, rely=0.231, relheight=0.223
                , relwidth=0.35)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Debits''')
        self.Labelframe1.configure(background="#800080")
        self.Labelframe1.configure(highlightbackground="#800080")
        self.Labelframe1.configure(highlightcolor="black")

        self.Label1_3 = tk.Label(self.Labelframe1)
        self.Label1_3.place(relx=0.042, rely=0.519, height=23, width=113
                , bordermode='ignore')
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#800080")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_3.configure(foreground="#ffffff")
        self.Label1_3.configure(highlightbackground="#800080")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(relief="groove")
        self.Label1_3.configure(text='''Withdrawals''')

        self.Label2_5 = tk.Label(self.Labelframe1)
        self.Label2_5.place(relx=0.583, rely=0.519, height=23, width=93
                , bordermode='ignore')
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(anchor='ne')
        self.Label2_5.configure(background="#800080")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_5.configure(foreground="#ffffff")
        self.Label2_5.configure(highlightbackground="#800080")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(justify='left')
        self.Label2_5.configure(relief="sunken")
        self.Label2_5.configure(text='''₦ 50,000''')

        self.Label1_4 = tk.Label(self.Labelframe1)
        self.Label1_4.place(relx=0.042, rely=0.741, height=23, width=113
                , bordermode='ignore')
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#800080")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_4.configure(foreground="#ffffff")
        self.Label1_4.configure(highlightbackground="#800080")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(relief="groove")
        self.Label1_4.configure(text='''Paidouts''')

        self.Label2_7 = tk.Label(self.Labelframe1)
        self.Label2_7.place(relx=0.583, rely=0.741, height=23, width=93
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(anchor='ne')
        self.Label2_7.configure(background="#800080")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_7.configure(foreground="#ffffff")
        self.Label2_7.configure(highlightbackground="#800080")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''₦ 30,000''')

        self.Label2_7 = tk.Label(self.Labelframe1)
        self.Label2_7.place(relx=0.042, rely=0.148, height=33, width=223
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(background="#800080")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_7.configure(foreground="#ffffff")
        self.Label2_7.configure(highlightbackground="#800080")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''₦ 80,000''')

        self.Labelframe1_6 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_6.place(relx=0.0, rely=0.479, relheight=0.223
                , relwidth=0.35)
        self.Labelframe1_6.configure(relief='groove')
        self.Labelframe1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_6.configure(foreground="black")
        self.Labelframe1_6.configure(text='''Upfronts''')
        self.Labelframe1_6.configure(background="#800080")
        self.Labelframe1_6.configure(highlightbackground="#800080")
        self.Labelframe1_6.configure(highlightcolor="black")

        self.Label1_5 = tk.Label(self.Labelframe1_6)
        self.Label1_5.place(relx=0.042, rely=0.519, height=23, width=113
                , bordermode='ignore')
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#800080")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_5.configure(foreground="#ffffff")
        self.Label1_5.configure(highlightbackground="#800080")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(relief="groove")
        self.Label1_5.configure(text='''Repaid''')

        self.Label2_7 = tk.Label(self.Labelframe1_6)
        self.Label2_7.place(relx=0.583, rely=0.519, height=23, width=93
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(anchor='ne')
        self.Label2_7.configure(background="#800080")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_7.configure(foreground="#ffffff")
        self.Label2_7.configure(highlightbackground="#800080")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''₦ 850,000''')

        self.Label1_6 = tk.Label(self.Labelframe1_6)
        self.Label1_6.place(relx=0.042, rely=0.741, height=23, width=113
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#800080")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_6.configure(foreground="#ffffff")
        self.Label1_6.configure(highlightbackground="#800080")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(relief="groove")
        self.Label1_6.configure(text='''Overdue''')

        self.Label2_8 = tk.Label(self.Labelframe1_6)
        self.Label2_8.place(relx=0.583, rely=0.741, height=23, width=93
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(anchor='ne')
        self.Label2_8.configure(background="#800080")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_8.configure(foreground="#ffffff")
        self.Label2_8.configure(highlightbackground="#800080")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(justify='left')
        self.Label2_8.configure(relief="sunken")
        self.Label2_8.configure(text='''₦ 130,000''')

        self.Label2_8 = tk.Label(self.Labelframe1_6)
        self.Label2_8.place(relx=0.042, rely=0.148, height=33, width=223
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#800080")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_8.configure(foreground="#ffffff")
        self.Label2_8.configure(highlightbackground="#800080")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(justify='left')
        self.Label2_8.configure(relief="sunken")
        self.Label2_8.configure(text='''₦ 980,000''')

        self.Labelframe1_8 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_8.place(relx=0.0, rely=0.719, relheight=0.273
                , relwidth=0.35)
        self.Labelframe1_8.configure(relief='groove')
        self.Labelframe1_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_8.configure(foreground="black")
        self.Labelframe1_8.configure(text='''Balances''')
        self.Labelframe1_8.configure(background="#800080")
        self.Labelframe1_8.configure(highlightbackground="#800080")
        self.Labelframe1_8.configure(highlightcolor="black")

        self.Label2_6 = tk.Label(self.Labelframe1_8)
        self.Label2_6.place(relx=0.583, rely=0.424, height=23, width=93
                , bordermode='ignore')
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(anchor='ne')
        self.Label2_6.configure(background="#800080")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_6.configure(foreground="#ffffff")
        self.Label2_6.configure(highlightbackground="#800080")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(justify='left')
        self.Label2_6.configure(relief="sunken")
        self.Label2_6.configure(text='''₦ 50,000''')

        self.Label2_8 = tk.Label(self.Labelframe1_8)
        self.Label2_8.place(relx=0.583, rely=0.606, height=23, width=93
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(anchor='ne')
        self.Label2_8.configure(background="#800080")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_8.configure(foreground="#ffffff")
        self.Label2_8.configure(highlightbackground="#800080")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(justify='left')
        self.Label2_8.configure(relief="sunken")
        self.Label2_8.configure(text='''₦ 30,000''')

        self.Label2_8 = tk.Label(self.Labelframe1_8)
        self.Label2_8.place(relx=0.042, rely=0.121, height=33, width=223
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#800080")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_8.configure(foreground="#ffffff")
        self.Label2_8.configure(highlightbackground="#800080")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(justify='left')
        self.Label2_8.configure(relief="sunken")
        self.Label2_8.configure(text='''₦ 1,080,000''')

        self.Label1_7 = tk.Label(self.Labelframe1_8)
        self.Label1_7.place(relx=0.042, rely=0.424, height=23, width=113
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#800080")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_7.configure(foreground="#ffffff")
        self.Label1_7.configure(highlightbackground="#800080")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(relief="groove")
        self.Label1_7.configure(text='''B-T-Os''')

        self.Label1_7 = tk.Label(self.Labelframe1_8)
        self.Label1_7.place(relx=0.042, rely=0.606, height=23, width=113
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#800080")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_7.configure(foreground="#ffffff")
        self.Label1_7.configure(highlightbackground="#800080")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(relief="groove")
        self.Label1_7.configure(text='''Deficits''')

        self.Label1_7 = tk.Label(self.Labelframe1_8)
        self.Label1_7.place(relx=0.042, rely=0.788, height=23, width=113
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#800080")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_7.configure(foreground="#ffffff")
        self.Label1_7.configure(highlightbackground="#800080")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(relief="groove")
        self.Label1_7.configure(text='''Excesses''')

        self.Label2_9 = tk.Label(self.Labelframe1_8)
        self.Label2_9.place(relx=0.583, rely=0.788, height=23, width=93
                , bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(anchor='ne')
        self.Label2_9.configure(background="#800080")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_9.configure(foreground="#ffffff")
        self.Label2_9.configure(highlightbackground="#800080")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(justify='left')
        self.Label2_9.configure(relief="sunken")
        self.Label2_9.configure(text='''₦ 30,000''')

if __name__ == '__main__':
    vp_start_gui()





