# ! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Dec 01, 2020 03:27:05 AM WAT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import dc_dashboard_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    dc_dashboard_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    dc_dashboard_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font13 = "-family {Times New Roman} -size 17 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("1047x646")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.01, rely=0.062, height=33, width=123)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(relief="groove")
        self.Label1.configure(text='''Areas''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.143, rely=0.062, height=33, width=103)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='ne')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(justify='left')
        self.Label2.configure(relief="sunken")
        self.Label2.configure(text='''006''')

        self.Frame1_11 = tk.Frame(top)
        self.Frame1_11.place(relx=0.344, rely=0.062, relheight=0.937
                , relwidth=0.654)
        self.Frame1_11.configure(relief='groove')
        self.Frame1_11.configure(borderwidth="2")
        self.Frame1_11.configure(relief="groove")
        self.Frame1_11.configure(background="#d9d9d9")
        self.Frame1_11.configure(highlightbackground="#ff8040")
        self.Frame1_11.configure(highlightcolor="black")

        self.Frame1_1 = tk.Frame(self.Frame1_11)
        self.Frame1_1.place(relx=0.38, rely=0.0, relheight=0.488, relwidth=0.62)
        self.Frame1_1.configure(relief='groove')
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief="groove")
        self.Frame1_1.configure(background="#d9d9d9")
        self.Frame1_1.configure(highlightbackground="#d9d9d9")
        self.Frame1_1.configure(highlightcolor="black")

        self.Canvas1_12 = tk.Canvas(self.Frame1_1)
        self.Canvas1_12.place(relx=0.012, rely=0.017, relheight=0.966
                , relwidth=0.976)
        self.Canvas1_12.configure(background="#ffff00")
        self.Canvas1_12.configure(borderwidth="2")
        self.Canvas1_12.configure(highlightbackground="#d9d9d9")
        self.Canvas1_12.configure(highlightcolor="black")
        self.Canvas1_12.configure(insertbackground="black")
        self.Canvas1_12.configure(relief="groove")
        self.Canvas1_12.configure(selectbackground="#c4c4c4")
        self.Canvas1_12.configure(selectforeground="black")

        self.Frame1_2 = tk.Frame(self.Frame1_11)
        self.Frame1_2.place(relx=0.38, rely=0.504, relheight=0.488
                , relwidth=0.62)
        self.Frame1_2.configure(relief='groove')
        self.Frame1_2.configure(borderwidth="2")
        self.Frame1_2.configure(relief="groove")
        self.Frame1_2.configure(background="#d9d9d9")
        self.Frame1_2.configure(highlightbackground="#d9d9d9")
        self.Frame1_2.configure(highlightcolor="black")

        self.Canvas1_3 = tk.Canvas(self.Frame1_2)
        self.Canvas1_3.place(relx=0.012, rely=0.017, relheight=0.966
                , relwidth=0.976)
        self.Canvas1_3.configure(background="#ffff00")
        self.Canvas1_3.configure(borderwidth="2")
        self.Canvas1_3.configure(highlightbackground="#d9d9d9")
        self.Canvas1_3.configure(highlightcolor="black")
        self.Canvas1_3.configure(insertbackground="black")
        self.Canvas1_3.configure(relief="groove")
        self.Canvas1_3.configure(selectbackground="#c4c4c4")
        self.Canvas1_3.configure(selectforeground="black")

        self.Labelframe1_7 = tk.LabelFrame(self.Frame1_11)
        self.Labelframe1_7.place(relx=0.0, rely=0.0, relheight=0.203
                , relwidth=0.355)
        self.Labelframe1_7.configure(relief='groove')
        self.Labelframe1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_7.configure(foreground="black")
        self.Labelframe1_7.configure(text='''Incomes''')
        self.Labelframe1_7.configure(background="#d9d9d9")
        self.Labelframe1_7.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_7.configure(highlightcolor="black")

        self.Label2_7 = tk.Label(self.Labelframe1_7)
        self.Label2_7.place(relx=0.576, rely=0.488, height=23, width=93
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(anchor='ne')
        self.Label2_7.configure(background="#d9d9d9")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_7.configure(foreground="#000000")
        self.Label2_7.configure(highlightbackground="#d9d9d9")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''₦ 50,000''')

        self.Label1_6 = tk.Label(self.Labelframe1_7)
        self.Label1_6.place(relx=0.041, rely=0.488, height=23, width=113
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(relief="groove")
        self.Label1_6.configure(text='''Savings''')

        self.Label2_5 = tk.Label(self.Labelframe1_7)
        self.Label2_5.place(relx=0.041, rely=0.163, height=33, width=223
                , bordermode='ignore')
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(background="#d9d9d9")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_5.configure(foreground="#000000")
        self.Label2_5.configure(highlightbackground="#d9d9d9")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(justify='left')
        self.Label2_5.configure(relief="sunken")
        self.Label2_5.configure(text='''₦ 3,000,000''')

        self.Label1_5 = tk.Label(self.Labelframe1_7)
        self.Label1_5.place(relx=0.041, rely=0.732, height=23, width=113
                , bordermode='ignore')
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(relief="groove")
        self.Label1_5.configure(text='''Transfers''')

        self.Label2_6 = tk.Label(self.Labelframe1_7)
        self.Label2_6.place(relx=0.576, rely=0.732, height=23, width=93
                , bordermode='ignore')
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(anchor='ne')
        self.Label2_6.configure(background="#d9d9d9")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_6.configure(foreground="#000000")
        self.Label2_6.configure(highlightbackground="#d9d9d9")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(justify='left')
        self.Label2_6.configure(relief="sunken")
        self.Label2_6.configure(text='''₦ 30,000''')

        self.Labelframe1_6 = tk.LabelFrame(self.Frame1_11)
        self.Labelframe1_6.place(relx=0.0, rely=0.231, relheight=0.223
                , relwidth=0.35)
        self.Labelframe1_6.configure(relief='groove')
        self.Labelframe1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_6.configure(foreground="black")
        self.Labelframe1_6.configure(text='''Debits''')
        self.Labelframe1_6.configure(background="#d9d9d9")
        self.Labelframe1_6.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_6.configure(highlightcolor="black")

        self.Label1_4 = tk.Label(self.Labelframe1_6)
        self.Label1_4.place(relx=0.042, rely=0.519, height=23, width=113
                , bordermode='ignore')
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(relief="groove")
        self.Label1_4.configure(text='''Withdrawals''')

        self.Label2_6 = tk.Label(self.Labelframe1_6)
        self.Label2_6.place(relx=0.583, rely=0.519, height=23, width=93
                , bordermode='ignore')
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(anchor='ne')
        self.Label2_6.configure(background="#d9d9d9")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_6.configure(foreground="#000000")
        self.Label2_6.configure(highlightbackground="#d9d9d9")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(justify='left')
        self.Label2_6.configure(relief="sunken")
        self.Label2_6.configure(text='''₦ 50,000''')

        self.Label1_5 = tk.Label(self.Labelframe1_6)
        self.Label1_5.place(relx=0.042, rely=0.741, height=23, width=113
                , bordermode='ignore')
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(relief="groove")
        self.Label1_5.configure(text='''Paidouts''')

        self.Label2_6 = tk.Label(self.Labelframe1_6)
        self.Label2_6.place(relx=0.583, rely=0.741, height=23, width=93
                , bordermode='ignore')
        self.Label2_6.configure(activebackground="#f9f9f9")
        self.Label2_6.configure(activeforeground="black")
        self.Label2_6.configure(anchor='ne')
        self.Label2_6.configure(background="#d9d9d9")
        self.Label2_6.configure(disabledforeground="#a3a3a3")
        self.Label2_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_6.configure(foreground="#000000")
        self.Label2_6.configure(highlightbackground="#d9d9d9")
        self.Label2_6.configure(highlightcolor="black")
        self.Label2_6.configure(justify='left')
        self.Label2_6.configure(relief="sunken")
        self.Label2_6.configure(text='''₦ 30,000''')

        self.Label2_8 = tk.Label(self.Labelframe1_6)
        self.Label2_8.place(relx=0.042, rely=0.148, height=33, width=223
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(background="#d9d9d9")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_8.configure(foreground="#000000")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(justify='left')
        self.Label2_8.configure(relief="sunken")
        self.Label2_8.configure(text='''₦ 80,000''')

        self.Labelframe1_7 = tk.LabelFrame(self.Frame1_11)
        self.Labelframe1_7.place(relx=0.0, rely=0.479, relheight=0.223
                , relwidth=0.35)
        self.Labelframe1_7.configure(relief='groove')
        self.Labelframe1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_7.configure(foreground="black")
        self.Labelframe1_7.configure(text='''Upfronts''')
        self.Labelframe1_7.configure(background="#d9d9d9")
        self.Labelframe1_7.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_7.configure(highlightcolor="black")

        self.Label1_6 = tk.Label(self.Labelframe1_7)
        self.Label1_6.place(relx=0.042, rely=0.519, height=23, width=113
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(relief="groove")
        self.Label1_6.configure(text='''Repaid''')

        self.Label2_8 = tk.Label(self.Labelframe1_7)
        self.Label2_8.place(relx=0.583, rely=0.519, height=23, width=93
                , bordermode='ignore')
        self.Label2_8.configure(activebackground="#f9f9f9")
        self.Label2_8.configure(activeforeground="black")
        self.Label2_8.configure(anchor='ne')
        self.Label2_8.configure(background="#d9d9d9")
        self.Label2_8.configure(disabledforeground="#a3a3a3")
        self.Label2_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_8.configure(foreground="#000000")
        self.Label2_8.configure(highlightbackground="#d9d9d9")
        self.Label2_8.configure(highlightcolor="black")
        self.Label2_8.configure(justify='left')
        self.Label2_8.configure(relief="sunken")
        self.Label2_8.configure(text='''₦ 850,000''')

        self.Label1_7 = tk.Label(self.Labelframe1_7)
        self.Label1_7.place(relx=0.042, rely=0.741, height=23, width=113
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(relief="groove")
        self.Label1_7.configure(text='''Overdue''')

        self.Label2_9 = tk.Label(self.Labelframe1_7)
        self.Label2_9.place(relx=0.583, rely=0.741, height=23, width=93
                , bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(anchor='ne')
        self.Label2_9.configure(background="#d9d9d9")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_9.configure(foreground="#000000")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(justify='left')
        self.Label2_9.configure(relief="sunken")
        self.Label2_9.configure(text='''₦ 130,000''')

        self.Label2_9 = tk.Label(self.Labelframe1_7)
        self.Label2_9.place(relx=0.042, rely=0.148, height=33, width=223
                , bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(background="#d9d9d9")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_9.configure(foreground="#000000")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(justify='left')
        self.Label2_9.configure(relief="sunken")
        self.Label2_9.configure(text='''₦ 980,000''')

        self.Labelframe1_8 = tk.LabelFrame(self.Frame1_11)
        self.Labelframe1_8.place(relx=0.0, rely=0.719, relheight=0.273
                , relwidth=0.35)
        self.Labelframe1_8.configure(relief='groove')
        self.Labelframe1_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_8.configure(foreground="black")
        self.Labelframe1_8.configure(text='''Balances''')
        self.Labelframe1_8.configure(background="#d9d9d9")
        self.Labelframe1_8.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_8.configure(highlightcolor="black")

        self.Label2_7 = tk.Label(self.Labelframe1_8)
        self.Label2_7.place(relx=0.583, rely=0.424, height=23, width=93
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(anchor='ne')
        self.Label2_7.configure(background="#d9d9d9")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_7.configure(foreground="#000000")
        self.Label2_7.configure(highlightbackground="#d9d9d9")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''₦ 50,000''')

        self.Label2_9 = tk.Label(self.Labelframe1_8)
        self.Label2_9.place(relx=0.583, rely=0.606, height=23, width=93
                , bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(anchor='ne')
        self.Label2_9.configure(background="#d9d9d9")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_9.configure(foreground="#000000")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(justify='left')
        self.Label2_9.configure(relief="sunken")
        self.Label2_9.configure(text='''₦ 30,000''')

        self.Label2_9 = tk.Label(self.Labelframe1_8)
        self.Label2_9.place(relx=0.042, rely=0.121, height=33, width=223
                , bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(background="#d9d9d9")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_9.configure(foreground="#000000")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(justify='left')
        self.Label2_9.configure(relief="sunken")
        self.Label2_9.configure(text='''₦ 1,080,000''')

        self.Label1_8 = tk.Label(self.Labelframe1_8)
        self.Label1_8.place(relx=0.042, rely=0.424, height=23, width=113
                , bordermode='ignore')
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(relief="groove")
        self.Label1_8.configure(text='''B-T-Os''')

        self.Label1_8 = tk.Label(self.Labelframe1_8)
        self.Label1_8.place(relx=0.042, rely=0.606, height=23, width=113
                , bordermode='ignore')
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(relief="groove")
        self.Label1_8.configure(text='''Deficits''')

        self.Label1_8 = tk.Label(self.Labelframe1_8)
        self.Label1_8.place(relx=0.042, rely=0.788, height=23, width=113
                , bordermode='ignore')
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(relief="groove")
        self.Label1_8.configure(text='''Excesses''')

        self.Label2_10 = tk.Label(self.Labelframe1_8)
        self.Label2_10.place(relx=0.583, rely=0.788, height=23, width=93
                , bordermode='ignore')
        self.Label2_10.configure(activebackground="#f9f9f9")
        self.Label2_10.configure(activeforeground="black")
        self.Label2_10.configure(anchor='ne')
        self.Label2_10.configure(background="#d9d9d9")
        self.Label2_10.configure(disabledforeground="#a3a3a3")
        self.Label2_10.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_10.configure(foreground="#000000")
        self.Label2_10.configure(highlightbackground="#d9d9d9")
        self.Label2_10.configure(highlightcolor="black")
        self.Label2_10.configure(justify='left')
        self.Label2_10.configure(relief="sunken")
        self.Label2_10.configure(text='''₦ 30,000''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.01, rely=0.139, relheight=0.859, relwidth=0.33)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.029, rely=0.144, relheight=0.297
                , relwidth=0.957)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Month''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#ff8040")
        self.Labelframe1.configure(highlightcolor="black")

        self.Label1_14 = tk.Label(self.Labelframe1)
        self.Label1_14.place(relx=0.061, rely=0.121, height=33, width=183
                , bordermode='ignore')
        self.Label1_14.configure(activebackground="#f9f9f9")
        self.Label1_14.configure(activeforeground="black")
        self.Label1_14.configure(background="#d9d9d9")
        self.Label1_14.configure(disabledforeground="#a3a3a3")
        self.Label1_14.configure(font=font13)
        self.Label1_14.configure(foreground="#000000")
        self.Label1_14.configure(highlightbackground="#d9d9d9")
        self.Label1_14.configure(highlightcolor="black")
        self.Label1_14.configure(relief="groove")
        self.Label1_14.configure(text='''December''')

        self.Label1_15 = tk.Label(self.Labelframe1)
        self.Label1_15.place(relx=0.667, rely=0.121, height=33, width=93
                , bordermode='ignore')
        self.Label1_15.configure(activebackground="#f9f9f9")
        self.Label1_15.configure(activeforeground="black")
        self.Label1_15.configure(background="#d9d9d9")
        self.Label1_15.configure(disabledforeground="#a3a3a3")
        self.Label1_15.configure(font="-family {Times New Roman} -size 17 -weight bold")
        self.Label1_15.configure(foreground="#000000")
        self.Label1_15.configure(highlightbackground="#d9d9d9")
        self.Label1_15.configure(highlightcolor="black")
        self.Label1_15.configure(relief="groove")
        self.Label1_15.configure(text='''2020''')

        self.Label1_6 = tk.Label(self.Labelframe1)
        self.Label1_6.place(relx=0.061, rely=0.424, height=23, width=113
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(relief="groove")
        self.Label1_6.configure(text='''Clients''')

        self.Label2_7 = tk.Label(self.Labelframe1)
        self.Label2_7.place(relx=0.485, rely=0.424, height=23, width=93
                , bordermode='ignore')
        self.Label2_7.configure(activebackground="#f9f9f9")
        self.Label2_7.configure(activeforeground="black")
        self.Label2_7.configure(anchor='ne')
        self.Label2_7.configure(background="#d9d9d9")
        self.Label2_7.configure(disabledforeground="#a3a3a3")
        self.Label2_7.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_7.configure(foreground="#000000")
        self.Label2_7.configure(highlightbackground="#d9d9d9")
        self.Label2_7.configure(highlightcolor="black")
        self.Label2_7.configure(justify='left')
        self.Label2_7.configure(relief="sunken")
        self.Label2_7.configure(text='''340''')

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.061, rely=0.788, height=28, width=45
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#bf6030")
        self.Button1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Prev''')

        self.Button1_9 = tk.Button(self.Labelframe1)
        self.Button1_9.place(relx=0.394, rely=0.788, height=28, width=65
                , bordermode='ignore')
        self.Button1_9.configure(activebackground="#ececec")
        self.Button1_9.configure(activeforeground="#000000")
        self.Button1_9.configure(background="#d9d9d9")
        self.Button1_9.configure(disabledforeground="#bf6030")
        self.Button1_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1_9.configure(foreground="#000000")
        self.Button1_9.configure(highlightbackground="#d9d9d9")
        self.Button1_9.configure(highlightcolor="black")
        self.Button1_9.configure(pady="0")
        self.Button1_9.configure(text='''Current''')

        self.Button1_10 = tk.Button(self.Labelframe1)
        self.Button1_10.place(relx=0.788, rely=0.788, height=28, width=45
                , bordermode='ignore')
        self.Button1_10.configure(activebackground="#ececec")
        self.Button1_10.configure(activeforeground="#000000")
        self.Button1_10.configure(background="#d9d9d9")
        self.Button1_10.configure(disabledforeground="#bf6030")
        self.Button1_10.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1_10.configure(foreground="#000000")
        self.Button1_10.configure(highlightbackground="#d9d9d9")
        self.Button1_10.configure(highlightcolor="black")
        self.Button1_10.configure(pady="0")
        self.Button1_10.configure(text='''Next''')

        self.Labelframe1_13 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_13.place(relx=0.029, rely=0.505, relheight=0.477
                , relwidth=0.957)
        self.Labelframe1_13.configure(relief='groove')
        self.Labelframe1_13.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_13.configure(foreground="black")
        self.Labelframe1_13.configure(text='''Sort and Search''')
        self.Labelframe1_13.configure(background="#d9d9d9")
        self.Labelframe1_13.configure(highlightbackground="#ff8040")
        self.Labelframe1_13.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.029, rely=0.018, relheight=0.099
                , relwidth=0.957)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Date and Time''')
        self.Labelframe1.configure(background="#d9d9d9")

        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.03, rely=0.364, height=23, width=103
                , bordermode='ignore')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#bf6030")
        self.Label3.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(relief="ridge")
        self.Label3.configure(text='''03 : 23 AM''')

        self.Label3_11 = tk.Label(self.Labelframe1)
        self.Label3_11.place(relx=0.394, rely=0.364, height=23, width=193
                , bordermode='ignore')
        self.Label3_11.configure(activebackground="#ffaa7f")
        self.Label3_11.configure(activeforeground="black")
        self.Label3_11.configure(background="#d9d9d9")
        self.Label3_11.configure(disabledforeground="#bf6030")
        self.Label3_11.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label3_11.configure(foreground="#000000")
        self.Label3_11.configure(highlightbackground="#ff8040")
        self.Label3_11.configure(highlightcolor="black")
        self.Label3_11.configure(relief="ridge")
        self.Label3_11.configure(text='''Tuesday 1, December 2020''')

if __name__ == '__main__':
    vp_start_gui()





