#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 05, 2020 11:40:49 PM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #800080
set vTcl(actual_gui_fg) #ffffff
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #004000
set vTcl(actual_gui_menu_fg) #ffff00
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #203f00
set vTcl(active_menu_fg) #111111
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 577x554
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab44 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {DC Office Details} -background $vTcl(actual_gui_bg) \
        -height 125 -width 270 
    vTcl:DefineAlias "$top.lab44" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab44
    label $site_3_0.lab45 \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -relief groove -text Office 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief groove -text Areas 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #ffaa7f -activeforeground black -background #0000ff \
        -disabledforeground #bf6030 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief sunken -text Owode 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #ffaa7f -activeforeground black -background #0000ff \
        -disabledforeground #bf6030 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief sunken -text 6 
    vTcl:DefineAlias "$site_3_0.lab50" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #ffaa7f -activeforeground black -background #0000ff \
        -disabledforeground #bf6030 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief sunken -text 1280 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief groove -text Clients 
    vTcl:DefineAlias "$site_3_0.lab66" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 10 -y 30 -width 100 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 10 -y 60 -width 100 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 128 -y 30 -width 130 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 127 -y 60 -width 130 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 127 -y 90 -width 130 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 10 -y 90 -width 100 -height 23 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab53 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Month \
        -background $vTcl(actual_gui_bg) -height 155 -width 271 
    vTcl:DefineAlias "$top.lab53" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab53
    label $site_3_0.lab54 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief groove -text {Active Clients} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #ffaa7f -activeforeground black -background #0000ff \
        -disabledforeground #bf6030 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief sunken -text 360 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief groove -text {December 2020} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Previous 
    vTcl:DefineAlias "$site_3_0.but58" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Next 
    vTcl:DefineAlias "$site_3_0.but59" "Button1_5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Current 
    vTcl:DefineAlias "$site_3_0.but60" "Button1_6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab54 \
        -in $site_3_0 -x 10 -y 70 -width 100 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 130 -y 70 -width 130 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 10 -y 30 -width 249 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 10 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 200 -y 120 -width 59 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 112 -y 120 -width 59 -height 28 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab61 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Account Highlight} -background $vTcl(actual_gui_bg) \
        -height 325 -width 570 
    vTcl:DefineAlias "$top.lab61" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab61
    labelframe $site_3_0.lab63 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text Accounts -background $vTcl(actual_gui_bg) -height 225 \
        -width 560 
    vTcl:DefineAlias "$site_3_0.lab63" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab63
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr72 \
        -background #ff8040 -height 187 -highlightbackground #ff8040 \
        -highlightcolor black -width 530 
    vTcl:DefineAlias "$site_4_0.scr72" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
        .top42.lab61.lab63.scr72.01 configure -columns {Col1}
        .top42.lab61.lab63.scr72.01 heading #0 -text {Tree}
        .top42.lab61.lab63.scr72.01 heading #0 -anchor center
        .top42.lab61.lab63.scr72.01 column #0 -width 257
        .top42.lab61.lab63.scr72.01 column #0 -minwidth 20
        .top42.lab61.lab63.scr72.01 column #0 -stretch 1
        .top42.lab61.lab63.scr72.01 column #0 -anchor w
        .top42.lab61.lab63.scr72.01 heading Col1 -text {Col1}
        .top42.lab61.lab63.scr72.01 heading Col1 -anchor center
        .top42.lab61.lab63.scr72.01 column Col1 -width 258
        .top42.lab61.lab63.scr72.01 column Col1 -minwidth 20
        .top42.lab61.lab63.scr72.01 column Col1 -stretch 1
        .top42.lab61.lab63.scr72.01 column Col1 -anchor w
    place $site_4_0.scr72 \
        -in $site_4_0 -x 10 -y 30 -width 534 -relwidth 0 -height 187 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $site_3_0.lab67 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief groove -text Areas 
    vTcl:DefineAlias "$site_3_0.lab67" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground #ffaa7f -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff8040 \
        -highlightcolor black -relief groove -text Clients 
    vTcl:DefineAlias "$site_3_0.lab68" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo70 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo70" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo71 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo71" "TCombobox1_4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 10 -y 90 -width 555 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 10 -y 30 -width 100 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 10 -y 60 -width 100 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo70 \
        -in $site_3_0 -x 120 -y 30 -width 143 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo71 \
        -in $site_3_0 -x 120 -y 58 -width 143 -height 24 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -y 0 -width 270 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 290 -y 0 -width 271 -relwidth 0 -height 155 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -y 220 -width 575 -relwidth 0 -height 325 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

