from .packed import *


class Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1047x646")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.01, rely=0.062, height=33,w=123)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(relief="groove")
        self.Label1.configure(text='''Areas''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.143, rely=0.062, height=33,w=103)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='ne')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(justify='left')
        self.Label2.configure(relief="sunken")
        self.Label2.configure(text='''006''')

        self.Frame1_11 = tk.Frame(top)
        self.Frame1_11.place(relx=0.344, rely=0.062, relh=0.937, relw=0.654)
        self.Frame1_11.configure(relief='groove')
        self.Frame1_11.configure(borderwidth="2")
        self.Frame1_11.configure(relief="groove")
        self.Frame1_11.configure(background="#d9d9d9")
        self.Frame1_11.configure(highlightbackground="#ff8040")
        self.Frame1_11.configure(highlightcolor="black")

        self.Frame1_1 = FramedCanvas(self.Frame1_11, relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="black", canvasConfig=dict(background="yellow", borderwidth="2", highlightbackground="#d9d9d9", highlightcolor="black", insertbackground="black", relief="groove", selectbackground="#c4c4c4", selectforeground="black"))
        self.Frame1_1.place(relx=0.38, rely=0.0, relh=0.488, relw=0.62)

        self.Frame1_2 = FramedCanvas(self.Frame1_11, relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="black", canvasConfig=dict(background="yellow", borderwidth="2", highlightbackground="#d9d9d9", highlightcolor="black", insertbackground="black", relief="groove", selectbackground="#c4c4c4", selectforeground="black"))
        self.Frame1_2.place(relx=0.38, rely=0.504, relh=0.488, relw=0.62)


        self.Frame2 = DC_Digits(self.Frame1_11, relief='groove', borderwidth="2", background="red")
        self.Frame2.place(relx=0.0, rely=0.0, relh=0.993, relw=0.369)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.01, rely=0.139, relh=0.859, relw=0.33)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#ff8040")
        self.Frame1.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.029, rely=0.144, relh=0.297, relw=0.957)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Month''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#ff8040")
        self.Labelframe1.configure(highlightcolor="black")

        self.Label1_14 = tk.Label(self.Labelframe1)
        self.Label1_14.place(relx=0.061, rely=0.121, height=33,w=183, bordermode='ignore')
        self.Label1_14.configure(activebackground="#f9f9f9")
        self.Label1_14.configure(activeforeground="black")
        self.Label1_14.configure(background="#d9d9d9")
        self.Label1_14.configure(disabledforeground="#a3a3a3")
        self.Label1_14.configure(font="-family {Times New Roman} -size 17 -weight bold")
        self.Label1_14.configure(foreground="#000000")
        self.Label1_14.configure(highlightbackground="#d9d9d9")
        self.Label1_14.configure(highlightcolor="black")
        self.Label1_14.configure(relief="groove")
        self.Label1_14.configure(text='''December''')

        self.Label1_15 = tk.Label(self.Labelframe1)
        self.Label1_15.place(relx=0.667, rely=0.121, height=33,w=93, bordermode='ignore')
        self.Label1_15.configure(activebackground="#f9f9f9")
        self.Label1_15.configure(activeforeground="black")
        self.Label1_15.configure(background="#d9d9d9")
        self.Label1_15.configure(disabledforeground="#a3a3a3")
        self.Label1_15.configure(font="-family {Times New Roman} -size 17 -weight bold")
        self.Label1_15.configure(foreground="#000000")
        self.Label1_15.configure(highlightbackground="#d9d9d9")
        self.Label1_15.configure(highlightcolor="black")
        self.Label1_15.configure(relief="groove")
        self.Label1_15.configure(text='''2020''')

        self.Label1_8 = tk.Label(self.Labelframe1)
        self.Label1_8.place(relx=0.061, rely=0.424, height=23,w=113, bordermode='ignore')
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(relief="groove")
        self.Label1_8.configure(text='''Clients''')

        self.Label2_9 = tk.Label(self.Labelframe1)
        self.Label2_9.place(relx=0.485, rely=0.424, height=23,w=93, bordermode='ignore')
        self.Label2_9.configure(activebackground="#f9f9f9")
        self.Label2_9.configure(activeforeground="black")
        self.Label2_9.configure(anchor='ne')
        self.Label2_9.configure(background="#d9d9d9")
        self.Label2_9.configure(disabledforeground="#a3a3a3")
        self.Label2_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label2_9.configure(foreground="#000000")
        self.Label2_9.configure(highlightbackground="#d9d9d9")
        self.Label2_9.configure(highlightcolor="black")
        self.Label2_9.configure(justify='left')
        self.Label2_9.configure(relief="sunken")
        self.Label2_9.configure(text='''340''')

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.061, rely=0.788, height=28,w=45, bordermode='ignore')
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#bf6030")
        self.Button1.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Prev''')

        self.Button1_9 = tk.Button(self.Labelframe1)
        self.Button1_9.place(relx=0.394, rely=0.788, height=28,w=65, bordermode='ignore')
        self.Button1_9.configure(activebackground="#ececec")
        self.Button1_9.configure(activeforeground="#000000")
        self.Button1_9.configure(background="#d9d9d9")
        self.Button1_9.configure(disabledforeground="#bf6030")
        self.Button1_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1_9.configure(foreground="#000000")
        self.Button1_9.configure(highlightbackground="#d9d9d9")
        self.Button1_9.configure(highlightcolor="black")
        self.Button1_9.configure(pady="0")
        self.Button1_9.configure(text='''Current''')

        self.Button1_10 = tk.Button(self.Labelframe1)
        self.Button1_10.place(relx=0.788, rely=0.788, height=28,w=45, bordermode='ignore')
        self.Button1_10.configure(activebackground="#ececec")
        self.Button1_10.configure(activeforeground="#000000")
        self.Button1_10.configure(background="#d9d9d9")
        self.Button1_10.configure(disabledforeground="#bf6030")
        self.Button1_10.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Button1_10.configure(foreground="#000000")
        self.Button1_10.configure(highlightbackground="#d9d9d9")
        self.Button1_10.configure(highlightcolor="black")
        self.Button1_10.configure(pady="0")
        self.Button1_10.configure(text='''Next''')

        self.Labelframe1_13 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_13.place(relx=0.029, rely=0.505, relh=0.477, relw=0.957)
        self.Labelframe1_13.configure(relief='groove')
        self.Labelframe1_13.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_13.configure(foreground="black")
        self.Labelframe1_13.configure(text='''Sort and Search''')
        self.Labelframe1_13.configure(background="#d9d9d9")
        self.Labelframe1_13.configure(highlightbackground="#ff8040")
        self.Labelframe1_13.configure(highlightcolor="black")

        self.Labelframe1_9 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_9.place(relx=0.029, rely=0.018, relh=0.099, relw=0.957)
        self.Labelframe1_9.configure(relief='groove')
        self.Labelframe1_9.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Labelframe1_9.configure(foreground="black")
        self.Labelframe1_9.configure(text='''Date and Time''')
        self.Labelframe1_9.configure(background="#d9d9d9")
        self.Labelframe1_9.configure(highlightbackground="#ff8040")
        self.Labelframe1_9.configure(highlightcolor="black")

        self.Label3 = tk.Label(self.Labelframe1_9)
        self.Label3.place(relx=0.03, rely=0.364, height=23,w=103, bordermode='ignore')
        self.Label3.configure(activebackground="#ffaa7f")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#bf6030")
        self.Label3.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#ff8040")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(relief="ridge")
        self.Label3.configure(text='''03 : 23 AM''')

        self.Label3_11 = tk.Label(self.Labelframe1_9)
        self.Label3_11.place(relx=0.394, rely=0.364, height=23,w=193, bordermode='ignore')
        self.Label3_11.configure(activebackground="#ffaa7f")
        self.Label3_11.configure(activeforeground="black")
        self.Label3_11.configure(background="#d9d9d9")
        self.Label3_11.configure(disabledforeground="#bf6030")
        self.Label3_11.configure(font="-family {Times New Roman} -size 11 -weight bold")
        self.Label3_11.configure(foreground="#000000")
        self.Label3_11.configure(highlightbackground="#ff8040")
        self.Label3_11.configure(highlightcolor="black")
        self.Label3_11.configure(relief="ridge")
        self.Label3_11.configure(text='''Tuesday 1, December 2020''')
