#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 06, 2020 03:31:56 AM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #800080
set vTcl(actual_gui_fg) #ffffff
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #004000
set vTcl(actual_gui_menu_fg) #ffff00
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #203f00
set vTcl(active_menu_fg) #111111
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 702x475
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab43 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Sort - Search} -background $vTcl(actual_gui_bg) -height 450 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 680 
    vTcl:DefineAlias "$top.lab43" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab43
    labelframe $site_3_0.lab44 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Date \
        -background $vTcl(actual_gui_bg) -height 95 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 310 
    vTcl:DefineAlias "$site_3_0.lab44" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab44
    button $site_4_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text 06/12/2020 
    vTcl:DefineAlias "$site_4_0.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -offrelief groove -overrelief ridge -relief groove \
        -text Year 
    vTcl:DefineAlias "$site_4_0.rad46" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Month 
    vTcl:DefineAlias "$site_4_0.rad47" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Day 
    vTcl:DefineAlias "$site_4_0.rad48" "Radiobutton2_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Week 
    vTcl:DefineAlias "$site_4_0.rad49" "Radiobutton2_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but45 \
        -in $site_4_0 -x 10 -y 20 -width 289 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad46 \
        -in $site_4_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.rad47 \
        -in $site_4_0 -x 80 -y 60 -width 70 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad48 \
        -in $site_4_0 -x 238 -y 60 -width 60 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad49 \
        -in $site_4_0 -x 160 -y 60 -width 70 -height 27 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab44
    labelframe $site_3_0.lab51 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Record \
        -background $vTcl(actual_gui_bg) -height 95 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 310 
    vTcl:DefineAlias "$site_3_0.lab51" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab51
    label $site_4_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Note 
    vTcl:DefineAlias "$site_4_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent54 \
        -background white -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent54" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Range 
    vTcl:DefineAlias "$site_4_0.lab43" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent44 \
        -background white -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent44" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab52 \
        -in $site_4_0 -x 10 -y 23 -width 56 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent54 \
        -in $site_4_0 -x 80 -y 23 -width 218 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab43 \
        -in $site_4_0 -x 10 -y 58 -width 55 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent44 \
        -in $site_4_0 -x 80 -y 58 -width 218 -height 26 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab51
    frame $site_3_0.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 195 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 315 
    vTcl:DefineAlias "$site_3_0.fra48" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra48
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $site_4_0.tNo49 \
        -width 304 -height 188 -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tNo49" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_0.tNo49.t0 \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.tNo49.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $site_4_0.tNo49 add $site_4_0.tNo49.t0 \
        -padding 0 -sticky nsew -state normal -text Sub-regions -image {} \
        -compound left -underline -1 
    set site_6_0  $site_4_0.tNo49.t0
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_6_0.scr50 \
        -background #d9d9d9 -height 75 -highlightbackground #d9d9d9 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_6_0.scr50" "Scrolledlistbox1_3" vTcl:WidgetProc "Toplevel1" 1

    $site_6_0.scr50.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font11 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #800080 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl:copy_lock $site_6_0.scr50
    place $site_6_0.scr50 \
        -in $site_6_0 -x 0 -y 0 -width 304 -relwidth 0 -height 162 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_4_0.tNo49.t1 \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.tNo49.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_4_0.tNo49 add $site_4_0.tNo49.t1 \
        -padding 0 -sticky nsew -state normal -text {Records Managers} \
        -image {} -compound left -underline -1 
    set site_6_1  $site_4_0.tNo49.t1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_6_1.scr53 \
        -background #d9d9d9 -height 75 -highlightbackground #d9d9d9 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_6_1.scr53" "Scrolledlistbox1_3" vTcl:WidgetProc "Toplevel1" 1

    $site_6_1.scr53.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font11 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #800080 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl:copy_lock $site_6_1.scr53
    place $site_6_1.scr53 \
        -in $site_6_1 -x 0 -y 0 -width 303 -height 162 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_4_0.tNo49
    place $site_4_0.tNo49 \
        -in $site_4_0 -x 0 -relx 0.0145 -y 5 -width 307 -relwidth 0 \
        -height 190 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra48
    place $site_3_0.lab44 \
        -in $site_3_0 -x 350 -y 20 -width 310 -relwidth 0 -height 95 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 350 -y 130 -width 310 -relwidth 0 -height 95 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra48 \
        -in $site_3_0 -x 350 -y 240 -width 312 -relwidth 0 -height 195 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab43
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 10 -width 680 -relwidth 0 -height 450 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

