#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 07, 2020 06:36:06 AM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #800080
set vTcl(actual_gui_fg) #ffffff
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #004000
set vTcl(actual_gui_menu_fg) #ffff00
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #203f00
set vTcl(active_menu_fg) #111111
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 702x475
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab43 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Sort - Search} -background $vTcl(actual_gui_bg) -height 450 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 680 
    vTcl:DefineAlias "$top.lab43" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab43
    labelframe $site_3_0.lab44 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Date \
        -background $vTcl(actual_gui_bg) -height 215 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 310 
    vTcl:DefineAlias "$site_3_0.lab44" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab44
    button $site_4_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font {-family {Times New Roman} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove -text 06/12/2020 
    vTcl:DefineAlias "$site_4_0.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -offrelief groove -overrelief ridge -relief groove \
        -text Year -value year 
    vTcl:DefineAlias "$site_4_0.rad46" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Month -value month 
    vTcl:DefineAlias "$site_4_0.rad47" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Day -value day 
    vTcl:DefineAlias "$site_4_0.rad48" "Radiobutton2_1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -relief groove -text Week -value week 
    vTcl:DefineAlias "$site_4_0.rad49" "Radiobutton2_2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #ffffff \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -offrelief groove -overrelief ridge -relief groove \
        -text {Day Name} -value year 
    vTcl:DefineAlias "$site_4_0.rad60" "Radiobutton1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent62 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_4_0.ent62" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but45 \
        -in $site_4_0 -x 10 -y 20 -width 289 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad46 \
        -in $site_4_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.rad47 \
        -in $site_4_0 -x 80 -y 60 -width 70 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad48 \
        -in $site_4_0 -x 238 -y 60 -width 60 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad49 \
        -in $site_4_0 -x 160 -y 60 -width 70 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad60 \
        -in $site_4_0 -x 10 -y 96 -width 101 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent62 \
        -in $site_4_0 -x 120 -y 97 -width 163 -height 21 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab51 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Record \
        -background $vTcl(actual_gui_bg) -height 95 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 310 
    vTcl:DefineAlias "$site_3_0.lab51" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab51
    label $site_4_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Note 
    vTcl:DefineAlias "$site_4_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Range 
    vTcl:DefineAlias "$site_4_0.lab43" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent44 \
        -background white -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent44" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {- to -} 
    vTcl:DefineAlias "$site_4_0.lab57" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent58 \
        -background white -disabledforeground #bf6030 \
        -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent58" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    text $site_4_0.tex59 \
        -background white \
        -font {-family {Javanese Text} -size 12 -weight bold} \
        -foreground black -height 4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 10 \
        -wrap word 
    .top42.lab43.lab51.tex59 configure -font "-family {Javanese Text} -size 12 -weight bold"
    .top42.lab43.lab51.tex59 insert end text
    vTcl:DefineAlias "$site_4_0.tex59" "Text1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab52 \
        -in $site_4_0 -x 6 -y 50 -width 56 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab43 \
        -in $site_4_0 -x 7 -y 19 -width 55 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent44 \
        -in $site_4_0 -x 67 -y 20 -width 68 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 129 -y 20 -width 55 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent58 \
        -in $site_4_0 -x 182 -y 21 -width 68 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex59 \
        -in $site_4_0 -x 67 -y 50 -width 184 -height 63 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 195 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 315 
    vTcl:DefineAlias "$site_3_0.fra48" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra48
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $site_4_0.tNo49 \
        -width 304 -height 188 -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tNo49" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_4_0.tNo49.t0 \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.tNo49.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $site_4_0.tNo49 add $site_4_0.tNo49.t0 \
        -padding 0 -sticky nsew -state normal -text Sub-regions -image {} \
        -compound left -underline -1 
    set site_6_0  $site_4_0.tNo49.t0
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_6_0.scr50 \
        -background #d9d9d9 -height 75 -highlightbackground #d9d9d9 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_6_0.scr50" "Scrolledlistbox1_3" vTcl:WidgetProc "Toplevel1" 1

    $site_6_0.scr50.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font11 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #800080 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl:copy_lock $site_6_0.scr50
    place $site_6_0.scr50 \
        -in $site_6_0 -x 0 -y 0 -width 304 -relwidth 0 -height 162 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_4_0.tNo49.t1 \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.tNo49.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_4_0.tNo49 add $site_4_0.tNo49.t1 \
        -padding 0 -sticky nsew -state normal -text Accounts -image {} \
        -compound left -underline -1 
    set site_6_1  $site_4_0.tNo49.t1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_6_1.scr43 \
        -background #d9d9d9 -height 157 -highlightbackground #d9d9d9 \
        -highlightcolor black -width 420 
    vTcl:DefineAlias "$site_6_1.scr43" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
        .top42.lab43.fra48.tNo49.t1.scr43.01 configure -columns {Col1}
        .top42.lab43.fra48.tNo49.t1.scr43.01 heading #0 -text {Tree}
        .top42.lab43.fra48.tNo49.t1.scr43.01 heading #0 -anchor center
        .top42.lab43.fra48.tNo49.t1.scr43.01 column #0 -width 142
        .top42.lab43.fra48.tNo49.t1.scr43.01 column #0 -minwidth 20
        .top42.lab43.fra48.tNo49.t1.scr43.01 column #0 -stretch 1
        .top42.lab43.fra48.tNo49.t1.scr43.01 column #0 -anchor w
        .top42.lab43.fra48.tNo49.t1.scr43.01 heading Col1 -text {Col1}
        .top42.lab43.fra48.tNo49.t1.scr43.01 heading Col1 -anchor center
        .top42.lab43.fra48.tNo49.t1.scr43.01 column Col1 -width 142
        .top42.lab43.fra48.tNo49.t1.scr43.01 column Col1 -minwidth 20
        .top42.lab43.fra48.tNo49.t1.scr43.01 column Col1 -stretch 1
        .top42.lab43.fra48.tNo49.t1.scr43.01 column Col1 -anchor w
    vTcl:copy_lock $site_6_1.scr43
    place $site_6_1.scr43 \
        -in $site_6_1 -x 0 -y 0 -width 303 -relwidth 0 -height 162 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_4_0.tNo49
    place $site_4_0.tNo49 \
        -in $site_4_0 -x 0 -relx 0.0145 -y 5 -width 307 -relwidth 0 \
        -height 190 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra48
    labelframe $site_3_0.lab43 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Personal Details} -background $vTcl(actual_gui_bg) -height 205 \
        -highlightbackground #d9d9d9 -highlightcolor black -width 260 
    vTcl:DefineAlias "$site_3_0.lab43" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab43
    label $site_4_0.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Name 
    vTcl:DefineAlias "$site_4_0.lab43" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Number 
    vTcl:DefineAlias "$site_4_0.lab45" "Label3_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Phone 
    vTcl:DefineAlias "$site_4_0.lab47" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text ID 
    vTcl:DefineAlias "$site_4_0.lab49" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Gender 
    vTcl:DefineAlias "$site_4_0.lab50" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -relief groove -text Address 
    vTcl:DefineAlias "$site_4_0.lab51" "Label3_3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_0.tCo56 \
        -font TkTextFont -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo56" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent63 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) -foreground #0000ff \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -validate all 
    vTcl:DefineAlias "$site_4_0.ent63" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent64 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) -foreground #0000ff \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -validate all 
    vTcl:DefineAlias "$site_4_0.ent64" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent65 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) -foreground #0000ff \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -validate all 
    vTcl:DefineAlias "$site_4_0.ent65" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent66 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) -foreground #0000ff \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -validate all 
    vTcl:DefineAlias "$site_4_0.ent66" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent67 \
        -background white -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_fixed_desc) -foreground #0000ff \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -validate all 
    vTcl:DefineAlias "$site_4_0.ent67" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab43 \
        -in $site_4_0 -x 10 -y 20 -width 63 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 10 -y 50 -width 63 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 10 -y 80 -width 63 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 10 -y 170 -width 63 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 10 -y 140 -width 63 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 10 -y 110 -width 63 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo56 \
        -in $site_4_0 -x 80 -y 140 -width 167 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent63 \
        -in $site_4_0 -x 80 -y 22 -width 167 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent64 \
        -in $site_4_0 -x 80 -y 50 -width 166 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent65 \
        -in $site_4_0 -x 80 -y 80 -width 166 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent66 \
        -in $site_4_0 -x 80 -y 110 -width 166 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent67 \
        -in $site_4_0 -x 80 -y 170 -width 166 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 340 -y 20 -width 310 -relwidth 0 -height 215 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 18 -y 229 -width 258 -relwidth 0 -height 118 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra48 \
        -in $site_3_0 -x 350 -y 240 -width 312 -relwidth 0 -height 195 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 18 -y 20 -width 258 -relwidth 0 -height 205 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab43
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 10 -width 680 -relwidth 0 -height 450 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

