#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 17, 2020 04:03:28 PM WAT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #40007f
set vTcl(actual_gui_menu_analog) #203f00
set vTcl(actual_gui_menu_bg) #004000
set vTcl(actual_gui_menu_fg) #ffff00
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #203f00
set vTcl(active_menu_fg) #111111
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m61" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 983x847
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "DC Subs"
    vTcl:DefineAlias "$top" "DCSubs" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab43 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text DC_Overview -background $vTcl(actual_gui_bg) -height 389 \
        -width 740 
    vTcl:DefineAlias "$top.lab43" "Labelframe1" vTcl:WidgetProc "DCSubs" 1
    set site_3_0 $top.lab43
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr66 \
        -background $vTcl(actual_gui_bg) -height 357 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 720 
    vTcl:DefineAlias "$site_3_0.scr66" "Scrolledtreeview1" vTcl:WidgetProc "DCSubs" 1
        .top42.lab43.scr66.01 configure -columns {Col1}
        .top42.lab43.scr66.01 heading #0 -text {Tree}
        .top42.lab43.scr66.01 heading #0 -anchor center
        .top42.lab43.scr66.01 column #0 -width 350
        .top42.lab43.scr66.01 column #0 -minwidth 20
        .top42.lab43.scr66.01 column #0 -stretch 1
        .top42.lab43.scr66.01 column #0 -anchor w
        .top42.lab43.scr66.01 heading Col1 -text {Col1}
        .top42.lab43.scr66.01 heading Col1 -anchor center
        .top42.lab43.scr66.01 column Col1 -width 351
        .top42.lab43.scr66.01 column Col1 -minwidth 20
        .top42.lab43.scr66.01 column Col1 -stretch 1
        .top42.lab43.scr66.01 column Col1 -anchor w
    place $site_3_0.scr66 \
        -in $site_3_0 -x 10 -y 20 -width 720 -relwidth 0 -height 357 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab46 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black -text Details \
        -background $vTcl(actual_gui_bg) -height 95 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 275 
    vTcl:DefineAlias "$top.lab46" "Labelframe1_1" vTcl:WidgetProc "DCSubs" 1
    set site_3_0 $top.lab46
    button $site_3_0.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {New Sub} 
    vTcl:DefineAlias "$site_3_0.but62" "Button1" vTcl:WidgetProc "DCSubs" 1
    button $site_3_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Delete Sub} 
    vTcl:DefineAlias "$site_3_0.but63" "Button1_4" vTcl:WidgetProc "DCSubs" 1
    label $site_3_0.lab64 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -relief groove -text {Total Subs} 
    vTcl:DefineAlias "$site_3_0.lab64" "Label1" vTcl:WidgetProc "DCSubs" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief sunken -text 76 
    vTcl:DefineAlias "$site_3_0.lab65" "Label1_5" vTcl:WidgetProc "DCSubs" 1
    place $site_3_0.but62 \
        -in $site_3_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 100 -y 60 -width 91 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 10 -y 20 -width 73 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 90 -y 20 -width 73 -height 23 -anchor nw \
        -bordermode ignore 
    set site_3_0 $top.m61
    menu $site_3_0 \
        -activebackground #203f00 -activeforeground #111111 \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab67 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground black \
        -text {Search and Sort} -background $vTcl(actual_gui_bg) -height 345 \
        -width 740 
    vTcl:DefineAlias "$top.lab67" "Labelframe2" vTcl:WidgetProc "DCSubs" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 450 -width 740 -relwidth 0 -height 389 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 10 -y 0 -width 275 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 10 -y 100 -width 740 -relwidth 0 -height 345 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

